name: auto CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: "0 17 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - uses: actions/cache@v1
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Update Deny Host
        run: |
          pwd
          python tools/main.py

      - name: Push to built branch
        uses: Automattic/action-commit-to-branch@master
        with:
          branch: 'main'
          commit_message: '🚀 update hosts'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  git_mirror:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        with:
          source-repo: 'git@github.com:frankwuzp/github-host.git'
          destination-repo: 'git@gitee.com:frankwuzp/github-host.git'
